language: csharp
mono: none
dotnet: 2.1.300
dist: trusty
sudo: required
os:
  - linux
  - osx

install:
  - dotnet restore

script:
  - dotnet build -c Release --no-restore --framework netstandard20 ./src
  - dotnet test  -c Release --no-restore --framework netcoreapp2.0 ./test
